(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"index_atlas_", frames: [[115,712,54,68],[77,885,21,45],[115,602,53,108],[0,602,113,187],[0,791,75,157],[77,791,67,92],[0,0,160,600]]}
];


// symbols:



(lib.sixteenblue = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.sixteencanlde = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.sixteengreens = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.sixteenmeats = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.sixteenpie = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();



(lib.sixteenspinach = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(5);
}).prototype = p = new cjs.Sprite();



(lib.sixteentable = function() {
	this.spriteSheet = ss["index_atlas_"];
	this.gotoAndStop(6);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.whiterectanglefade = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("EgQFAy9MAAAhl5MAgLAAAMAAABl5g");

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.whiterectanglefade, new cjs.Rectangle(-103,-326,206.1,652.2), null);


(lib.sixteentable_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.sixteentable();
	this.instance.parent = this;
	this.instance.setTransform(-80,-300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.sixteentable_1, new cjs.Rectangle(-80,-300,160,600), null);


(lib.sixteenspinach_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.sixteenspinach();
	this.instance.parent = this;
	this.instance.setTransform(-33.5,-46);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.sixteenspinach_1, new cjs.Rectangle(-33.5,-46,67,92), null);


(lib.sixteenpie_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.sixteenpie();
	this.instance.parent = this;
	this.instance.setTransform(-37.5,-78.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.sixteenpie_1, new cjs.Rectangle(-37.5,-78.5,75,157), null);


(lib.sixteenmeats_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.sixteenmeats();
	this.instance.parent = this;
	this.instance.setTransform(-56.5,-93.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.sixteenmeats_1, new cjs.Rectangle(-56.5,-93.5,113,187), null);


(lib.sixteengreens_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.sixteengreens();
	this.instance.parent = this;
	this.instance.setTransform(-26.5,-54);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.sixteengreens_1, new cjs.Rectangle(-26.5,-54,53,108), null);


(lib.sixteencanlde_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.sixteencanlde();
	this.instance.parent = this;
	this.instance.setTransform(-10.5,-22.5);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.sixteencanlde_1, new cjs.Rectangle(-10.5,-22.5,21,45), null);


(lib.sixteenblue_1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.sixteenblue();
	this.instance.parent = this;
	this.instance.setTransform(-27,-34);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.sixteenblue_1, new cjs.Rectangle(-27,-34,54,68), null);


(lib.seventeenvidrollover = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#B63100").s().p("AnzCoQhFAAgygyQgxgwABhGQgBhFAxgwQAygyBFAAIPnAAQBGAAAwAyQAyAwAABFQAABGgyAwQgwAyhGAAg");
	this.shape.setTransform(0,-50,0.966,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.seventeenvidrollover, new cjs.Rectangle(-64.5,-66.7,129,33.5), null);


(lib.seventeenrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#D63900").s().p("AnzCoQhFAAgygyQgxgwABhGQgBhFAxgwQAygyBFAAIPnAAQBGAAAwAyQAyAwAABFQAABGgyAwQgwAyhGAAg");
	this.shape.setTransform(0,-50,0.966,1);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.seventeenrectangle, new cjs.Rectangle(-64.5,-66.7,129,33.5), null);


(lib.seventeenordernow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgMAjQgHgDgFgFQgFgFgDgHQgCgHAAgIQAAgHACgHQADgHAFgFQAFgFAGgDQAIgDAGAAQAIABAGACQAHADAEAEQAEAFADAHQADAHAAAIIAAABIAAADIg4AAQAAAFACAEIAFAGQADAEAEABQAEACAEAAQAHAAAFgDQAGgDACgFIAKAIQgFAHgIAEIgIACIgJABQgHAAgHgCgAAVgFIgBgIQgCgEgCgDQgCgCgEgCQgEgCgFAAIgHACQgEACgDACQgDADgCAEQgCADAAAFIApAAIAAAAg");
	this.shape.setTransform(34.4,-49.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgTAkIAAg3IAAgHIgBgIIAOAAIAAAGIAAAHIABAAQADgHAEgDIAHgEIAGgBIAGABIgBANIgGAAQgFAAgEABQgEACgBADQgDAEgBADQgBAEAAAFIAAAkg");
	this.shape_1.setTransform(27.9,-49.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgOAiQgHgCgFgFQgFgFgDgHQgDgHAAgIQAAgIADgGQADgHAFgFQAFgFAHgDQAHgDAHAAQAIAAAHADQAHADAFAFQAGAFACAHQADAGAAAIQAAAIgDAHQgCAHgGAFQgFAFgHACQgHADgIAAQgHAAgHgDgAgJgXQgFADgDADQgDADgBAFQgCAEAAAFQAAAFACAEQABAFADAEQADAEAFACQAEABAFAAQAGAAAEgBQAFgCADgEQADgEABgFQACgEAAgFQAAgFgCgEQgBgFgDgDQgDgDgFgDQgEgCgGAAQgFAAgEACg");
	this.shape_2.setTransform(20.1,-49.7);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgDApQgGgGAAgLIAAglIgNAAIAAgMIANAAIAAgUIANAAIAAAUIATAAIAAAMIgTAAIAAAkQAAAGADADQACADAFAAIAFgBIAEgBIAAAMIgGABIgGAAQgKAAgEgFg");
	this.shape_3.setTransform(13,-50.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgPAiQgIgDgEgHIAKgIQADAEAFADQAFADAEAAIAGgBIAEgBIAEgDIABgGQAAgEgFgDQgFgCgIgCIgHgDQgEgBgDgBQgDgCgCgEQgCgDAAgFQAAgFADgFQACgEADgCIAJgFIAJgBQAHAAAIADQAHADAEAGIgKAIQgDgEgEgCQgEgDgGAAIgDABIgFACIgCADIgBAEQAAAEADACIAMAFIAJADQAEABADABQAEADABADQACAEAAAFQABAGgDAEQgCAFgFADQgDACgGABQgEABgGAAQgHAAgIgDg");
	this.shape_4.setTransform(7.3,-49.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgOAkQgFgBgEgCQgDgDgDgEQgCgFAAgGIABgHQABgDADgCQADgEAIgCQAGgDAJgBIASgBIAAgCQgBgHgFgEQgEgEgIAAQgFAAgGACQgFADgEADIgHgJQAFgFAIgDQAIgDAHAAQAIAAAFACQAGADADADQAFAFABAEQACAFAAAGIAAAfIAAAHIABAGIgNAAIgBgKIAAAAQgFAGgGADQgFADgHAAIgJgBgAADACIgJACQgFABgDADQgCADAAAEIABAGIADADIAFABIAFABQAEAAADgCQAFAAACgDQADgEABgDQACgEAAgEIAAgFIgEAAg");
	this.shape_5.setTransform(-3.9,-49.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgQA3QgGgDgFgFQgFgFgCgHQgDgHAAgIQAAgIADgHQACgFAFgGQAFgFAGgCQAHgDAIAAQAIAAAGADQAGAEAEAFIAAg1IAPAAIAABxIgOAAIAAgMQgEAHgHADQgHAEgHAAQgIAAgHgDgAgJgDQgEADgDACQgDAEgCAEIgBAKIABAKQACAEADAEQADAEAEACQAFACAEAAQAGAAAEgCQAFgCADgEQADgDACgFQABgFAAgFIgBgKIgFgIQgDgCgFgDQgEgCgGAAQgEAAgFACg");
	this.shape_6.setTransform(-16.6,-51.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AASAkIAAgmIAAgIIgDgHIgFgFQgDgCgFAAQgIABgFAFQgGAHABAKIAAAlIgPAAIAAg3IAAgHIAAgIIAOAAIAAAGIAAAGIABAAIADgFIAGgEIAGgEIAGgBQAHAAAGACQAEADAEAEQADAEABAFQACAGAAAFIAAArg");
	this.shape_7.setTransform(-25.4,-49.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgGA1IAAhGIANAAIAABGgAgGgkQgCgDgBgEQABgEACgDQADgCADAAQAEAAACACQADADAAAEQAAAEgDADQgCACgEAAQgDAAgDgCg");
	this.shape_8.setTransform(-31.7,-51.4);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AggA1IAAhpIBBAAIAAANIgyAAIAAAhIAvAAIAAALIgvAAIAAAwg");
	this.shape_9.setTransform(-37.5,-51.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.seventeenordernow, new cjs.Rectangle(-44.2,-62.8,85,22.4), null);


(lib.mainbutton = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#006F46").s().p("EgQFAzRMAAAhmhMAgLAAAMAAABmhg");
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(3).to({_off:false},0).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = null;


(lib.holidaymainssides = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgJBEIgOgDIgEADIgEAAIgCAAIgDgCQgEgEgEgLQgEgKAAgKQAAgDADgDQACgDADAAQAGAAAGAKIAFAIQAEAGAHADQAGACAHAAQAJABAFgFQAFgEAAgIQAAgKgVgLIgIgDQgUgKgHgIQgHgJAAgMQAAgRAMgLQALgKATAAIAJAAIAJACIAGgDIAEAAQAGAAAGAKQAGALAAAKQAAAFgCACQgCADgDAAQgDAAgDgCQgDgCgEgHQgFgIgFgDQgFgEgIABQgGgBgFAFQgEAEAAAHQAAAGAEAFQAFAEAPAIIACABQAkAQAAAWQAAASgOAMQgOAMgVAAg");
	this.shape.setTransform(50.9,33.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgGBOQgHgCgEgFQgFgEgCgGQgCgIAAgTIAAhFIgMAAIgDgBIgBgDIAAgEQAAgDANgMIAGgFIAFgEQANgMAFAAIADABQABAAAAABQAAAAAAAAQABABAAAAQAAAAAAABIAAAYIAdAAIAEACIABAEIAAADQAAAEgBABQAAABgBAAQAAAAgBABQAAAAgBAAQgBAAAAAAIgbAAIgCABIgBADIAABAQAAARADADQADAFAHAAQAEAAAHgDIAJgCQAAAAABABQABAAAAAAQABAAAAABQABAAAAAAQABABAAAAQABABAAAAQAAABAAAAQAAABAAABQAAAHgLAGQgLAHgOAAQgHAAgGgCg");
	this.shape_1.setTransform(40.8,32.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgpAxQgTgTAAgcQAAgdATgUQATgTAcAAQAaAAAPANQAOAPAAAYQAAAIgDADQgBACgKABIgyAAQgEgBgCgCQgCgCgBgEQABgDACgCQACgCAEAAIAbAAIAGgBQABAAAAAAQAAgBABAAQAAAAAAgBQAAgBAAAAQAAgNgJgJQgIgIgMAAQgPAAgHAOQgIANABATQgBAUALAOQALAPAPAAQAKAAAGgCQAGgCAHgFIAEgDQAHgGAEAAQADABABABQABABAAAAQAAABABAAQAAABAAAAQAAABAAABQAAACgDAGQgDAEgFAEQgMAKgKADQgLAEgNABQgagBgSgSg");
	this.shape_2.setTransform(29.4,33.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgqAxQgSgTAAgcQAAgdATgUQATgTAdAAQAZAAAOANQAPAPAAAYQAAAIgDADQgBACgLABIgwAAQgEgBgDgCQgCgCAAgEQAAgDACgCQADgCAEAAIAaAAIAGgBQABAAAAAAQAAgBABAAQAAAAAAgBQAAgBAAAAQAAgNgIgJQgJgIgMAAQgOAAgIAOQgHANAAATQAAAUAKAOQAKAPAQAAQAJAAAHgCQAGgCAHgFIAFgDQAGgGAEAAQACABACABQABABAAAAQAAABABAAQAAABAAAAQAAABAAABQAAACgDAGQgDAEgGAEQgLAKgKADQgLAEgNABQgagBgTgSg");
	this.shape_3.setTransform(15.7,33.8);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAIAOIgPgoQgIgSgGgDIgEgCQgHgDAAgEQAAgGAGgCQAHgCAUAAQASAAAGACQAGACAAAGIgBADIgCADIgEACQgGACAAACIADAJIAKAbIALAYQADAHACAAQACgBACgDIAGgMIAOggQAFgMAAgEIgBgFIgDgDIgEgBQgGgDAAgEQAAgFAGgCQAGgCAQAAQANAAAGACQAFACAAAFQAAAGgGACIgFABQgGADgMAbIgCAHIgGALQgdBDgJAAQgJAAgWg1gAhLAHIgEgIIgJgVQgIgWgGgDIgEgCQgHgDAAgEQAAgGAGgCQAHgCAVAAQASAAAGACQAGACAAAGIgBADIgCADIgEACQgGACAAACIADAMIAKAYIALAYQADAGACABQAEgBADgHIAFgKIADgEQAAAAABAAQAAAAABgBQAAAAABAAQABAAAAAAQADAAACABQACADAAADQAAADgEAHQgNAegGAKQgGAKgFAAQgJAAgZg8g");
	this.shape_4.setTransform(-1.6,34);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgfBdQgPgDgJgFQgFgDgDgLQgEgLAAgPQAAgGADgDQACgDAEAAQAGAAAHALIADAGQAIAOAKAHQAJAGAOAAQANAAAKgIQAKgIAAgNQAAgSgmgRIgEgBQgfgNgLgMQgKgLAAgSQAAgYARgPQARgPAcAAIAOACIASAEIAFgEIAFgBQADAAADACQACACADAFQAEAIADAIQACAJAAAGQAAAFgCACQgCADgEAAQgGAAgHgKIgCgCQgHgKgJgEQgIgFgLAAQgOAAgIAHQgJAGAAAMQAAALAHAHQAHAHAbAMIAGACQAXAKAKAIQAHAHAEAIQAEAJAAAKQAAAbgTAPQgSAPggAAQgQAAgOgEg");
	this.shape_5.setTransform(-20,31);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhOBOQgYgSAAgeQAAgRAIgNQAIgLARgMIAAgBQgFgGgDgHQgDgGAAgGQAAgVAPgNQAPgNAYAAQAPAAALAGQALAGAAAJQAAACgDACQgDADgDAAIgKgEQgJgDgIAAQgKAAgGAHQgHAGAAAMQAAAFACAEIAFAGIAJAGIAIADIACABIABACQAAADgFAFQgFAGgEgBIgFgBIgJgDQgHAHgEAHQgEAKAAAMQAAAZAQAPQAQARAZgBQAVABANgLQANgLAAgSQAAgLgGgGQgFgHgJAAQgJAAgGAGQgFAFAAAIIAAACIAAACIgCABIgCAAQgEAAgDgEQgDgDAAgHQAAgSA5gbIADgBQAPgHAIgIQAIgIAAgJQAAgGgDgDQgEgDgHAAIgFAAIgEABQgDAAgCgCQgBAAAAgBQAAAAAAgBQgBAAAAgBQAAgBAAgBQAAgFAHgEQAHgDAMgBQANABAIAHQAJAIAAAMQAAARgOANQgOANgdALQAMAEAGAKQAGAKAAANQAAAJgEAKQgEAJgHAIQgMANgRAGQgSAHgXAAQgnAAgYgTg");
	this.shape_6.setTransform(-45,31);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgJBEIgOgDIgEADIgEAAIgCAAIgDgCQgEgEgEgLQgEgKAAgJQAAgFADgCQACgDADAAQAGAAAGALIAFAHQAEAFAHAEQAGACAHAAQAJAAAFgEQAFgEAAgIQAAgLgVgKIgIgEQgUgJgHgIQgHgJAAgMQAAgRAMgLQALgKATAAIAJABIAJABIAGgCIAEgBQAGAAAGAKQAGAKAAALQAAAFgCACQgCADgDAAQgDAAgDgCQgDgDgEgGQgFgIgFgDQgFgEgIAAQgGAAgFAFQgEAEAAAHQAAAGAEAEQAFAFAPAIIACABQAkARAAAVQAAASgOAMQgOAMgVAAg");
	this.shape_7.setTransform(68.4,3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgpAxQgTgTAAgcQAAgeATgTQATgTAdgBQAYAAAPAPQAPAOAAAYQAAAIgCADQgCADgLAAIgwAAQgEAAgDgDQgDgCABgDQgBgEADgCQADgBAEAAIAaAAIAHgBQAAgBAAAAQAAAAABgBQAAAAAAgBQAAgBAAgBQAAgMgIgJQgJgIgLAAQgQAAgHAOQgIANAAATQAAATALAPQALAPAPAAQAKAAAGgCQAHgDAGgEIAEgEQAHgEADAAQADgBADACQAAABAAAAQAAABABAAQAAABAAAAQAAABAAABQAAADgDAEQgDAFgFAEQgMAKgLAEQgKADgMAAQgbAAgSgSg");
	this.shape_8.setTransform(56.1,3);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("Ag4BOQgPgRAAgcQgBggATgSQAQgVAdAAIAIABQAEACACADQACACABAEQgBAGgIAAIgDAAIgDAAQgPAAgJAMQgIAKAAAVQAAAWAJANQAJAPAPAAQANAAAHgIQAIgHAAgPIAAgkIAAg6QAAgKgCgDQgBgDgGgCIgCgBQgJgCAAgFQAAgEADgDQAEgCAKgDIAOgFIAMgBQAFAAABACQACADAAAFIAAAIIgCBPIACA2QABAMACACIAJADQAGACABAEQAAAGgTAGIgOADIgKABQgDAAgCgCQgBgCAAgEIAAgGIgBgDIAAgBIgEADIgGAFQgIAFgGADQgIADgHAAQgZAAgPgSg");
	this.shape_9.setTransform(42,0.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgWBcQgHgCAAgFQAAgFAHgCIADgBQADgCACgEQABgFAAgKIAAgJIAAgKIAAgNQAAgVgBgFQgBgGgDgBIgGgDQgIgDAAgDQAAgDADgDIAIgEIATgHIANgCQAEAAABACQACADAAAGIAAAIIAAAGIgBAfIAAABIgBAgIABASQABAEADACIAFADQAHABAAAGQAAAFgHACQgGACgRAAQgTgBgGgCgAgPhAQgGgFAAgHQAAgHAGgGQAHgEAIAAQAIgBAFAFQAGAFAAAHQAAAHgGAFQgGAFgIAAQgJAAgFgEg");
	this.shape_10.setTransform(30.1,0.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgfBdQgPgDgJgFQgFgDgDgLQgEgLAAgPQAAgGADgDQACgDAEAAQAGAAAHALIADAGQAIAOAKAHQAJAGAOAAQANAAAKgIQAKgIAAgNQAAgSgmgRIgEgBQgfgNgLgMQgKgLAAgSQAAgYARgPQARgPAcAAIAOACIASAEIAFgEIAFgBQADAAADACQACACADAFQAEAIADAIQACAJAAAGQAAAFgCACQgCADgEAAQgGAAgHgKIgCgCQgHgKgJgEQgIgFgLAAQgOAAgIAHQgJAGAAAMQAAALAHAHQAHAHAbAMIAGACQAXAKAKAIQAHAHAEAIQAEAJAAAKQAAAbgTAPQgSAPggAAQgQAAgOgEg");
	this.shape_11.setTransform(18.9,0.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgNAnQgBAAAAAAQgBgBAAAAQAAgBAAAAQgBAAAAgBIADgFIADgEIAHgOQADgGAAgDIgBgDIgFgCQgGgDgDgEQgDgFgBgHQABgJAFgFQAGgGAHAAQAIAAAGAIQAGAHgBAMQAAAJgCAIQgEAJgIAOIgHAKQgDAEgCAAQgDAAgDgCg");
	this.shape_12.setTransform(1.1,9.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgJBEIgOgDIgEADIgEAAIgCAAIgDgCQgEgEgEgLQgEgKAAgJQAAgFADgCQACgDADAAQAGAAAGALIAFAHQAEAFAHAEQAGACAHAAQAJAAAFgEQAFgEAAgIQAAgLgVgKIgIgEQgUgJgHgIQgHgJAAgMQAAgRAMgLQALgKATAAIAJABIAJABIAGgCIAEgBQAGAAAGAKQAGAKAAALQAAAFgCACQgCADgDAAQgDAAgDgCQgDgDgEgGQgFgIgFgDQgFgEgIAAQgGAAgFAFQgEAEAAAHQAAAGAEAEQAFAFAPAIIACABQAkARAAAVQAAASgOAMQgOAMgVAAg");
	this.shape_13.setTransform(-8.5,3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AARBAQgGgCAAgFQAAgFAGgCIAGgCQACgCABgFQACgGAAgOQAAgogFgLQgGgKgNAAQgGAAgHAEQgGAEgEAHQgCAGgBAKIgBAjQAAAMABAEQABAEACACIAGACQAGACAAAFQAAAFgGADQgHABgRAAQgUAAgGgCQgHgCAAgFQAAgFAHgCIAEgCQACgBACgFQACgEgBgKIAAgJIAAgKIAAgNQAAgUgBgGQgBgGgCgCIgHgCQgIgDAAgEQABgDACgCIAIgFIASgGIAOgCQAEAAABACQACACAAAEIAAAJIABABIAAABIABgBIABAAIACgDIADgCQAOgNAQAAQAJAAAJAEQAIAEAGAHQAGAHACAKQADAJAAAVIAAARIAAAIIAAAIIABANQABAEADABIAEACQAHACgBAFQAAAFgFACQgHACgTAAQgSAAgHgCg");
	this.shape_14.setTransform(-21.8,2.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgWBcQgHgCAAgFQAAgFAHgCIADgBQADgCACgEQABgFAAgKIAAgJIAAgKIAAgNQAAgVgBgFQgBgGgDgBIgGgDQgIgDAAgDQAAgDADgDIAIgEIATgHIANgCQAEAAABACQACADAAAGIAAAIIAAAGIgBAfIAAABIgBAgIABASQABAEADACIAFADQAHABAAAGQAAAFgHACQgGACgRAAQgTgBgGgCgAgPhAQgGgFAAgHQAAgHAGgGQAHgEAIAAQAIgBAFAFQAGAFAAAHQAAAHgGAFQgGAFgIAAQgJAAgFgEg");
	this.shape_15.setTransform(-33.2,0.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAXA9IgHgHIgGADQgPALgQAAQgSAAgNgLQgLgLAAgSQAAgVAPgLQAPgLAbAAQAGAAADACQADACABAFQAAAGgJAAQgNAAgIAGQgHAHAAALQAAAKAGAGQAIAGAKAAQAMAAAGgFQAFgGAAgNIAAgxQABgLgGgGQgEgHgJAAQgGAAgFADQgGADgGAGIgCADQgIAKgJAAQgFAAgDgDQgDgDAAgGQAAgMAPgJQAPgIAYAAQAOAAAKAEQAKAEAFAHQAEAFACAIQACAIAAASIAAApIABALQABAEADABIAEABQAIACAAAEQAAAHgJAFQgIAFgMAAQgFAAgHgHg");
	this.shape_16.setTransform(-43.6,3);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAwBbQgHgBAAgHQAAgFAIgDIAGgDQACgCABgFIABgXIAAgHIAAg2IgBghIgQAqQgmBjgIAAQgEAAgHgNQgIgOgSgqIgchBIgBAzIgBAjIABAYQABAGACABIAFADQAJADAAAFQAAAGgHACQgHACgQABQgOgBgGgCQgHgCAAgGQAAgEAHgDQAHgEABgCQACgHACghQACggAAgqIAAgDQAAgOgBgFQgBgEgDgCIgGgDQgJgDAAgFQAAgGAGgCQAGgBATAAIASAAIAFABQADACAJAXIAHATIAEAJQAfBNACgBQADAAAMgbQALgbAQguIADgIQAFgOAEgFQACgCAFAAIASgBQARAAAGABQAGACAAAGQAAAFgIADIgDABQgEADgCAFQgBAFAAATIABBKIADAmQABACAGACIACACIAFADQABAAAAABQAAAAAAABQABAAAAABQAAABAAAAQAAAHgHABQgIACgVABQgUgBgHgCg");
	this.shape_17.setTransform(-62.4,0.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("Ag7BVQgGgEAAgJQAAgGAEgFQAFgFAGABIAGABIAEACIAEAFQADAFACAAQAHAAAHgKQAHgJAAgKQAAgLgKgVIgBgDIgVgtIgMgZQgCgEgHgEIgBAAIgFgDQgCgCAAgDQAAgFAHgDQAHgCATAAQASAAAHACQAGACAAAFIgBAFIgCACIgFACQgFACAAACIADAKIAKAaIAKAYQAEAGABAAQACAAADgFIAIgVIAKgaQADgJAAgEQAAgDgHgEQgIgEAAgEQAAgEAGgCQAGgCAPAAQAPAAAGACQAFACAAAFQAAAFgHACIgFACQgIAEgIAWIgEAKIgQAoQgWA2gNARQgNAQgTAAQgKAAgGgGg");
	this.shape_18.setTransform(39.1,-25.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AAXA9IgHgHIgFADQgQALgQAAQgTAAgLgLQgMgLAAgSQAAgVAPgLQAPgLAbAAQAGAAADACQAEACgBAFQAAAGgIAAQgMAAgJAGQgIAHAAALQAAAKAIAGQAGAGAMAAQAMAAAFgFQAGgGAAgNIAAgxQgBgLgEgGQgFgHgJAAQgGAAgGADQgFADgFAGIgDADQgIAKgIAAQgGAAgDgDQgDgDAAgGQAAgMAPgJQAPgIAYAAQANAAAKAEQALAEAFAHQAEAFACAIQACAIAAASIAAApIABALQACAEACABIAEABQAIACAAAEQAAAHgIAFQgKAFgLAAQgFAAgHgHg");
	this.shape_19.setTransform(25.8,-27.8);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("Ag4BOQgQgRAAgcQABggARgTQARgTAcgBIAJABQAEABADAEQABACAAADQABAIgJgBIgDAAIgEAAQgOAAgIAMQgJALAAAUQAAAWAKAOQAJANAOAAQANABAIgIQAHgHAAgPIAAgkIAAg6QAAgKgBgDQgDgEgEgBIgEgCQgHgCAAgEQAAgEADgDQADgCAJgEIAPgDIAMgCQAEAAACACQACADAAAGIAAAHIgCBPIABA2QABAMACACIAJADQAIABgBAFQABAGgUAGIgMAEIgKAAQgEAAgCgBQgBgCAAgFIAAgGIAAgDIgBgBIgEADIgGAFQgHAFgHADQgHADgJAAQgYAAgPgSg");
	this.shape_20.setTransform(11.4,-30.7);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgWBcQgHgCAAgFQAAgFAHgCIADgCQADgBACgEQABgFAAgKIAAgJIAAgKIAAgOQAAgUgBgFQgBgGgDgBIgGgDQgIgCAAgEQAAgEADgCIAIgEIATgGIANgDQAEAAABADQACACAAAGIAAAIIAAAFIgBAgIAAABIgBAgIABASQABAFADABIAFADQAHACAAAEQAAAFgHADQgGABgRAAQgTAAgGgCgAgPhAQgGgFAAgHQAAgHAGgFQAHgFAIgBQAIAAAFAFQAGAFAAAHQAAAHgGAFQgGAFgIAAQgJAAgFgEg");
	this.shape_21.setTransform(-0.5,-30.7);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgVBdQgGgCAAgFQAAgEAFgDIAHgDQACgDABgHIABgaIAAgUIgBgYIAAgKQAAgggBgKQgBgJgDgCIgIgDQgIgCAAgFQAAgDADgCQACgCAKgDIARgFIAMgCQAEAAACACQACADAAAGIgBAKQgBAuAAAuIABAsQAAAKADACIAHAEQAGACAAAFQAAAFgHADQgGABgRAAQgTAAgGgCg");
	this.shape_22.setTransform(-7.9,-30.8);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AguAwQgTgSAAgdQAAgdAUgTQATgUAcAAQAcABASARQASASAAAdQAAAdgTAVQgTATgcAAQgcAAgSgTgAgYgmQgIALAAARQAAAZALARQALARAPAAQANABAHgLQAIgLAAgRQAAgZgLgRQgLgSgOAAQgNAAgIALg");
	this.shape_23.setTransform(-18.6,-27.8);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AAdBbQgIgBAAgHQABgFAHgDIAHgDQABgCABgHIABgfIAAgSIgBgFQgCgCgGgBQgGgCgYAAIgbABQgHABgCACIgCADIgBAKIAAALIACAfQABAHACACIAFADQAIADAAAFQAAAHgHABQgHACgUAAQgVAAgHgCQgIgBABgHQAAgEAIgEIAFgDQADgBACgRIABg2IgBgxQgCgUgCgCQAAgBgIgEQgGgCAAgFQAAgGAFgBQAGgCAYAAQAWAAAGACQAGABAAAGQAAAFgIADIgFADQgDABAAAJIgCAlQABAGAEACQAFACATgBIAKAAIAcAAQAHgBACgCIACgDIAAgEIAAgHIgBgfQgBgHgBgBIgHgDQgHgDgBgFQABgGAGgBQAGgCAWAAQAYAAAFACQAHABgBAGQAAAFgIADIgGADQgCACgCARIAAA1IAAAxQACATABADQACACAGACQAIAEgBAEQAAAHgHABQgHACgVAAQgUAAgHgCg");
	this.shape_24.setTransform(-35.7,-30.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.holidaymainssides, new cjs.Rectangle(-76.1,-48.2,152.3,96.4), null);


(lib.greyrectangle = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#999999").ss(1,1,1).p("EgL3guZIXvAAMAAABc0I3vAAg");
	this.shape.setTransform(0,0,1.046,1.008);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.greyrectangle, new cjs.Rectangle(-80.5,-300.5,161,601), null);


(lib.Path = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#231F20").s().p("AqNYMQktiAjpjoQjpjph/ktQiEk4AAlWQAAlVCEk4QB/ktDpjpQDpjpEth/QE4iEFVAAQFWAAE4CEQEtB/DpDpQDoDpCAEtQCEE4AAFVQAAFWiEE4QiAEtjoDpQjpDoktCAQk4CElWAAQlVAAk4iEg");
	this.shape.setTransform(168,168);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Path, new cjs.Rectangle(0,0,336,336), null);


(lib.deliciiousmemories = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgVAtQgJgEgIgHIgBgCIgBgBIACgDIADgEIADgCIADgBQABAAAAAAQABAAAAAAQABABAAAAQABAAABABIAGAEIAIAEQAEABAGAAIAHAAIAHgCIAGgFQACgCAAgFQAAgDgCgDQgDgCgFgBIgJgCIgKgCIgLgCQgGgCgEgBQgFgDgCgFQgDgFAAgHQAAgHAEgGQAEgFAGgEIAMgFIANgBIAJAAIAJADIAJADIAIAGIAAABIABACQAAAAgBABQAAAAAAABQAAAAAAAAQgBABAAAAIgDADIgDACIgEABIgDAAQgEgFgGgCQgGgDgGAAIgGABIgHACIgEAEQgCADgBADQAAAGAFACQAFACAGABIAOACQAIABAGADQAIACAEAFQAFAFgBAKQAAAIgDAGQgFAFgFAEQgHAEgHACQgHACgGAAQgLAAgKgEg");
	this.shape.setTransform(32.2,9.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AggAvIgCgBQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAhVQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIACgBIBBAAIADACIABADIAAACIAAAEIgBADIgDACIgvAAIgDACIgCADIAAAMIACADIADACIAeAAQABAAAAAAQABAAAAAAQAAAAAAAAQABABAAAAIABADIAAAEIAAACQAAAEgEABIgeAAQAAAAAAAAQgBAAAAAAQgBABAAAAQgBAAAAABQAAAAgBAAQAAABAAAAQAAABAAAAQgBAAAAABIAAAPIACADIADAAIAvAAQAEADAAADIAAADIAAADIgBAEIgDABg");
	this.shape_1.setTransform(23.5,9.6);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAAAxIgCAAQgEAAgCgDIAAhbIADgCIADgBIADAAIADAAQAEAAABAEIAABZIgCADIgEABg");
	this.shape_2.setTransform(16.4,9.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAYAvIgDAAIgCgBIgBgBIgQgZIgCgDIgEgBIgMAAIgDABIgBADIAAAYQAAAAgBAAQAAABAAAAQAAAAAAABQgBAAAAAAIgEABIgDAAIgDAAIgEAAQgBgBAAAAQAAAAgBgBQAAAAAAgBQAAgBAAgBIAAhVQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIACgBIAoAAQAHAAAGACQAGACAEAEQAFAFADAFQACAHAAAHQAAAIgDAFQgDAEgEADIgGAFQgDACAAACIAAACIAEAFIAFAIIAFAIIADAEQgBABAAAAQAAAAAAABQAAAAAAAAQgBABAAAAIgDACIgEABIgCABgAgTgeQAAAAgBABQAAAAAAABQAAAAAAABQAAAAAAABIAAAVQAAABAAAAQAAABAAABQAAAAAAAAQABABAAAAQAAAAABABQABAAAAAAQABAAAAAAQABAAAAAAIATAAIAHAAIAGgEQACgBABgDQACgDAAgEQAAgIgFgEIgGgDIgHgBIgTAAIgEABg");
	this.shape_3.setTransform(9.9,9.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgJAwIgKgDQgEgCgEgDIgIgFQgHgHgDgJIgEgJIgBgKIABgJIAEgKQADgIAHgHIAIgGIAIgEIAKgDIAJgBIAKABQAFAAAFADQAJAEAHAGQAHAHADAIQAEAJABAKIgCAKIgDAJQgDAJgHAHQgHAGgJAEIgKADIgKABIgJgBgAgLgdQgGACgFAFQgEAEgCAGQgEAGAAAGQAAAHAEAGQACAFAEAFQAFAEAGADQAGADAFgBQAGABAGgDQAGgDAEgEQAFgFACgFQADgGAAgHQAAgGgDgGQgCgGgFgEQgEgFgGgCQgGgCgGgBQgFABgGACg");
	this.shape_4.setTransform(-0.9,9.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAfAvIgEgBQgBAAAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBIAAgrIgBgBIgDgBQAAAAAAAAQgBAAAAAAQgBABAAAAQAAABgBAAIgPAYQgBACgCAAIgDgBIgCgBIgNgYQAAAAgBgBQAAAAAAAAQAAAAgBAAQAAAAAAAAIgDAAIgBABIAAArQgBADgDAAIgGABIgCAAIgCgBIgCgCIgBgBIAAhWQAAAAABgBQAAAAAAgBQABAAAAgBQABAAABAAIAFAAIAEAAIACACIAWAmQACADACAAIADgBIACgCIAWglQADgDAFAAIAEAAIADACIAABXQAAAAAAAAQAAABAAAAQgBABAAAAQAAAAgBAAIgCACIgDAAg");
	this.shape_5.setTransform(-11.7,9.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgfAvIgDgBQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAhVQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAABAAIADgBIBAAAIADACIABADIAAACIAAAEIgBADIgDACIgvAAIgEACIgBADIAAAMIABADIAEACIAeAAQABAAAAAAQABAAAAAAQAAAAAAAAQABABAAAAIABADIAAAEIAAACQAAAEgEABIgdAAQgBAAAAAAQgBAAAAAAQgBABAAAAQgBAAAAABQAAAAgBAAQAAABAAAAQAAABAAAAQgBAAAAABIAAAPIABADIAEAAIAvAAQADADABADIAAADIAAADIgCAEIgCABg");
	this.shape_6.setTransform(-21.1,9.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AAgAvIgFgBQgBAAAAAAQgBAAAAgBQAAAAAAgBQAAAAAAgBIAAgrIgBgBIgDgBQAAAAAAAAQgBAAAAAAQgBABAAAAQAAABgBAAIgPAYQgBACgCAAIgDgBIgCgBIgNgYQAAAAgBgBQAAAAAAAAQAAAAgBAAQAAAAAAAAIgDAAIgBABIAAArQgBADgDAAIgGABIgCAAIgCgBIgCgCIgBgBIAAhWQAAAAABgBQAAAAAAgBQABAAAAgBQABAAABAAIAFAAIAEAAIACACIAXAmQABADACAAIADgBIACgCIAWglQADgDAFAAIAEAAIADACIAABXQAAAAAAAAQAAABAAAAQgBABAAAAQAAAAAAAAIgDACIgDAAg");
	this.shape_7.setTransform(-31.4,9.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgVAtQgKgEgHgHIgBgCIgBgBIACgDIACgEIAEgCIADgBQABAAAAAAQABAAAAAAQABABAAAAQABAAABABIAFAEIAJAEQAEABAGAAIAHAAIAHgCIAGgFQACgCAAgFQAAgDgCgDQgDgCgEgBIgKgCIgKgCIgMgCQgFgCgEgBQgFgDgCgFQgCgFgBgHQABgHADgGQAEgFAGgEIAMgFIANgBIAJAAIAJADIAJADIAHAGIABABIABACQAAAAgBABQAAAAAAABQAAAAAAAAQgBABAAAAIgDADIgDACIgEABIgDAAQgEgFgGgCQgFgDgHAAIgGABIgGACIgGAEQgCADAAADQABAGAEACQAFACAGABIAOACQAIABAGADQAIACAEAFQAEAFAAAKQAAAIgDAGQgFAFgGAEQgFAEgHACQgIACgGAAQgKAAgLgEg");
	this.shape_8.setTransform(55.4,-10.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgPAuQgIgDgGgFQgFgGgDgHQgCgEgBgEIgBgIIAAgaIAAgaQAAAAAAAAQAAgBABAAQAAAAAAgBQAAAAABAAIADgCIADAAIADAAIAEABQABAAAAAAQABABAAAAQAAAAABABQAAAAAAABIAAAwQAAAFABAFQACAFADAEIAIAGQAEACAFAAQAGAAAEgCQAFgCADgEQADgEACgFQACgFAAgFIAAgwQAAAAAAgBQAAgBAAAAQAAgBABAAQAAgBAAAAIAFgBIADAAIAEABIADABIABADIAAA0IgBAIQgBAEgCAEQgDAHgFAGQgGAFgIADQgHADgJAAQgIAAgHgDg");
	this.shape_9.setTransform(45.5,-10.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgJAwIgKgDQgFgCgDgDIgIgFQgHgHgDgJIgDgJIgCgKIACgJIADgKQADgIAHgHIAIgGIAIgEIAKgDIAJgBIAKABQAFAAAFADQAJAEAHAGQAGAHAEAIQAFAJAAAKIgBAKIgEAJQgEAJgGAHQgHAGgJAEIgKADIgKABIgJgBgAgLgdQgGACgEAFQgFAEgCAGQgDAGgBAGQABAHADAFQACAGAFAFQAEAEAGADQAGADAFgBQAGABAGgDQAGgDAFgEQAEgFACgGQADgFAAgHQAAgGgDgGQgCgGgEgEQgFgFgGgCQgGgCgGgBQgFABgGACg");
	this.shape_10.setTransform(34.7,-10.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAAAxIgCAAQgEAAgCgDIAAhbIADgCIADgBIADAAIADAAQAEAAABAEIAABZIgCADIgEABg");
	this.shape_11.setTransform(27.1,-10.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgDAwIgKgDIgJgEIgHgGIgGgHIgFgIQgEgJAAgLQAAgJAEgJIAFgJIAGgHQAHgHAJgDIAKgDIAJgBIAKABIALADIAKAGIAHAHIABACQAAABAAABQAAAAgBABQAAAAAAABQAAAAgBABIgEACIgDACIgDABQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBgBIgFgEIgHgEQgFgCgGAAQgGAAgGACQgGADgEAEQgFAFgCAGQgDAGAAAFQAAAHADAGQACAGAFAEQAEAEAGADQAGADAGAAQAHAAAGgDQAHgDAEgFIAEgBIADABIADACIADADIACADIgBACQgDAEgFADQgEAEgFACIgKADIgLABIgJgBg");
	this.shape_12.setTransform(20,-10.3);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AAAAxIgCAAQgEAAgCgDIAAhbIADgCIADgBIADAAIADAAQAEAAABAEIAABZIgCADIgEABg");
	this.shape_13.setTransform(12.9,-10.3);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AggAwIgDgBIgBgEIAAhVQAAgBAAAAQAAAAAAgBQAAAAABAAQAAgBAAAAIADgCIADAAIADAAIAFABQAAAAABABQAAAAABAAQAAABAAAAQABABAAABIAABBIAAADIACADQACACADAAIArAAIADABIABADIABADIAAADQAAADgBACQgBAAAAABQAAAAgBAAQAAABgBAAQgBAAgBAAg");
	this.shape_14.setTransform(6.9,-10.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgfAvIgEgBQAAAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAhVQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAAAAAIAEgBIBBAAIACACIAAADIABACIAAAEIgBADIgCACIgxAAIgDACIgBADIAAAMIABADIAEACIAeAAQABAAAAAAQABAAAAAAQAAAAAAAAQABABAAAAIAAADIABAEIAAACQAAAEgEABIgdAAQgBAAAAAAQgBAAAAAAQgBABAAAAQgBAAAAABQAAAAgBAAQAAABAAAAQAAABAAAAQAAAAgBABIAAAPIABADIAEAAIAwAAQACADAAADIAAADIAAADIgBAEIgCABg");
	this.shape_15.setTransform(-2.1,-10.2);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgnAvIgDgBQgBAAAAgBQAAAAgBAAQAAgBAAAAQAAAAAAgBIAAhUQAAgBAAAAQAAgBAAAAQABgBAAAAQAAgBABAAIACgBIAkAAIAIABIAKADQAJACAIAHQAGAGAEAIIADAKIABAJQAAAKgEAKIgEAIIgHAGIgIAFIgIAFQgJADgJAAgAgZgcQAAAAgBABQAAAAAAABQAAAAAAABQgBAAAAABIAAAzQAAAAABAAQAAABAAAAQAAABAAAAQABAAAAABIADAAIASAAQAFAAAGgBQAHgDAEgEQAEgEADgGQADgFAAgHQAAgGgDgGQgDgFgEgEQgEgEgHgDQgGgCgFAAIgRAAQgBAAAAABQgBAAAAAAQgBAAAAAAQgBABAAAAg");
	this.shape_16.setTransform(-12.1,-10.2);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AggAvIgDgBQAAAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIAAhVQAAgBAAAAQAAgBAAAAQABAAAAgBQAAAAAAAAIADgBIBCAAIACACIAAADIABACIAAAEIgBADIgCACIgxAAIgDACIAAADIAAAMIAAADIAEACIAfAAQAAAAAAAAQABAAAAAAQAAAAAAAAQABABAAAAIAAADIABAEIAAACQAAAEgDABIgfAAQAAAAAAAAQgBAAAAAAQgBABAAAAQgBAAAAABQAAAAgBAAQAAABAAAAQAAABAAAAQAAAAAAABIAAAPIAAADIAEAAIAwAAQACADAAADIAAADIAAADIgBAEIgCABg");
	this.shape_17.setTransform(-26,-10.2);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AAaAxIgEAAQgBgBAAAAQgBAAAAAAQgBgBAAAAQAAAAAAgBIgYgkIgDgCIgEgBIgEACQgBAAAAABQgBAAAAABQAAAAgBABQAAAAAAABIAAAeQAAAAAAAAQAAABAAAAQAAABgBAAQAAAAAAAAIgEACIgEAAIgDABQgFAAAAgFIAAhYIACgCIADgBIADAAIADAAQAEAAACADIAAAeQAAABAAAAQAAAAABABQAAAAAAAAQAAABABAAIAEABQAAAAABAAQAAAAABgBQAAAAABAAQAAgBABAAIAaggIABgBIADAAIACAAIAEACIADADIABADIgBACIgXAaIgBADIAAADIAAACIABACIAeAoIAAACIAAABIgBACIgDACIgEACg");
	this.shape_18.setTransform(-35.2,-10.2);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AAlAwIgCAAIgGgBQAAAAgBAAQAAgBgBAAQAAAAgBgBQAAAAAAgBIgGgNIgBgCIgDgBIgfAAIgBABIgBABIgCABIgBAAIgFANIgBACIgDABIgDAAIgCAAIgDAAIgDAAIgCgBIgBgCIAmhYQAAgBAAAAQABAAAAAAQAAgBABAAQAAAAAAAAIADgBIADABQABAAABAAQAAAAABABQAAAAABAAQAAAAAAABIAmBYIAAAAIgBADIgEABgAAAgOIgBABIgCADIgCAEIgBAGIgDAEIgCAEIAAACIAAACIADABIASAAIABgBIABgCIgBgEIgDgGIgEgJIgCgEIgCgBg");
	this.shape_19.setTransform(-44.8,-10.2);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAgAvIgFgBQgBAAAAAAQgBAAAAgBQAAAAAAgBQgBAAAAgBIAAgrIAAgBIgCgBQgBAAAAAAQgBAAAAAAQgBABAAAAQAAABgBAAIgOAYQgCACgCAAIgDgBIgCgBIgNgYQAAAAgBgBQAAAAAAAAQAAAAgBAAQAAAAAAAAIgDAAIgBABIAAArQgBADgDAAIgGABIgCAAIgCgBIgCgCIgBgBIAAhWQAAAAABgBQAAAAAAgBQABAAAAgBQABAAAAAAIAGAAIADAAIADACIAXAmQABADACAAIADgBIACgCIAWglQADgDAEAAIAFAAIADACIAABXQAAAAAAAAQAAABAAAAQgBABAAAAQAAAAAAAAIgDACIgEAAg");
	this.shape_20.setTransform(-54.6,-10.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.deliciiousmemories, new cjs.Rectangle(-62,-18.8,124.1,37.6), null);


(lib.whitelogo = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AqoZMQk7iEjyjzQjxjxiFk6QiKlGAAljQAAljCKlGQCFk6DxjzQDzjxE6iFQFFiKFjAAQFkAAFFCKQE7CFDxDxQDyDzCFE6QCKFGAAFjQAAFjiKFGQiFE6jyDxQjxDzk7CEQlFCKlkAAQljAAlFiKgALSMVIgBANQAAAPAKAAIAzAAQAMAAgBAKIAACUQAAAHAGACQADACAKABQAKgBAEgCQAFgCAAgIIgBiTQABgKAMAAIAxAAQALAAAAgSQAAgSgMAAIigAAQgGAAgDAIgADSONIBBBGQAHAHATABQANAAAFgFQAGgFgIgIIhOhWQgJgLAKgHIBAg6QAJgKgMgMQgMgMgNALIhKBEQgFAFgEABQgFADgKAAQgKAAAAgOIAAg2QAAgMgRAAQgMAAgDACQgFACgBAIIAAC1QAAANARAAQAVAAAAgNIAAg7QAAgGADgFQAEgEAFAAQATgBALAKgAhwOXQALAAAFAJIAhAyQAFAIARABQAPAAAEgFQAFgEgFgHIgigzQgEgFAHgHQAPgKAIgIQAOgQAAgYQABgfgVgUQgUgSggAAIhsAAQgJAAAAAIIAAC6QAAAMANAAIAPgBQAKgBAAgHIgBgxQABgEADgDQADgDAEAAgAmQOxQAIAAACAHIANAbQAEAHAPABQAIgBAGgCQAJgDgDgGIhXi7QgFgJgLAAQgMAAgEAKIhaC5QgFAMAWAAQASAAADgHIANgXQAEgLAIAAgArGNkIANBsQAAAFAGADQAFADAEAAQAYAAgBgLIgVi2QgCgIgEgDQgDgCgGAAQgLAAgEAIIg8BPQgHAIgEAAQgEABgGgIIg3hPQgGgIgKAAQgKgBgEAFQgDADgCAJIgVCxQAAAGAGADQAFADAFAAQAUAAACgLIANhpQACgIAEABQAEAAADACIAtA9QAEAHAHAAQAFAAAFgGIAwg/QADgEAEABQAFgBACAHgAGyMaIAACwQAAAOANAAICcAAQAKABAAgSQAAgSgKAAIh6AAQgJAAgBgLIAAgdQAAgLAMAAIBFAAQAKAAAAgRQABgTgLABIhHAAQgJAAgBgKIAAgbQAAgJAJAAIB6AAQAHAAADgGQABgEAAgJQAAgJgBgEQgDgEgGAAIicAAQgNAAAAANgAT4IwQgNAOABASQgBASANANQANANATAAQASAAANgNQANgNAAgSQAAgSgNgOQgNgNgSABQgTgBgNANgAP5JKQAlAMA0AAQBUAAAzgtQAygtAAhJQAAghgMgeQgMgegWgXQgUgVgXgSQgWgRgzgkIgqgdQgbgVgMgSQgJgMAAgXQAAgaARgQQASgPAeAAQAsAAAjAbQAPALAFAGQAHAIAOAVQAKAOAMAAQALABAGgHQAIgFgBgJQABgIgCgEIgUhcQgFgXgTAAQgIAAgKAGQgLAIgIAAIgMgCIgWgEQgjgIgmAAQhGAAgrAlQgrAmAAA+QAAAzAgAmQAUAVARAPIBNA3QBBAsAaAdQAcAfgBAhQABAigaAUQgaAWgpAAQglAAgigSQghgTgWgfIgMgRQgJgLgMAAQgLAAgIAIQgIAIAAALQAAAKACAHIAWBUQAEAQAFAHQAGAGALAAQAJAAALgIQAJgJAJABIASAEgAjRF+QAHAAACALIABADQAYBeBFA1QBHA2BlAAQCCAABMhQQBMhRAAiIQAAiFhMhQQhNhQh+ABQhogBhHA3QhFA1gYBgIAAABQgCALgHAAQgIAAgBgKQgYhhhHg2QhHg3hoABQiBAAhLBQQhLBQAACIQgBCFBMBQQBMBQB+AAQBoAABIg2QBHg2AYhfIAAgBQACgLAGAAIABAAgAFnIeQgGAHAAAKQAAANAJAFQAIAEAUADQBeANBrgBQBFABAxgOQAvgOAlgeQAwglAZg+QAZg9AAhOQAAhFgTg3QgVg5glgmQgngng1gSQg1gShOAAQhrAAheANQgUADgIAEQgJAFAAANQAAAJAGAIQAFAGAJABIARAAQAKAAAFALQADAKgBAXIAAF5QABAYgDAKQgFALgKAAIgRAAQgJAAgFAHgAyyIfQgHAHABAKQgBAOAJAFQAJAGAWAAICcAAQAYAAAJgGQAJgFAAgOQAAgKgHgHQgGgGgKAAIgTAAQgMAAgGgMQgCgFAAgbIgBiLQAAgZAJgFQAEgEAeAAIBGAAQAaAAAIAEQAHADACANIABAFQAEAWATABQANgBAGgIQAFgKAAgWIAAhHQAAgWgFgJQgGgJgNAAQgUAAgDAVIgBAGQgBAMgIAEQgHADgbAAIhGAAQgeAAgEgDQgJgFAAgaIAAhlQABghAIgJQAJgJAiAAIBtAAQAgAAANAEQAOAFAGAPQAFAOADAFQAIAOAOAAQAMAAAFgJQAGgJgEgQIgMg8QgFgUgZgBIlwAAQgWABgIAFQgJAGAAAOQgBAJAHAHQAHAHAIAAIASAAQAEAAAEAEQAEADABAGQAEAKAAAXIAAF8QAAAXgDAJQgEAMgKAAIgSAAQgJAAgGAGgACorXQACAKgJADQgpAOgmATQgmATgZASQg5AoggBCQgfBEAABaQgBCLBPBTQBOBUCEAAQCHAABQhVQBPhUAAiOQAAilhohNQg7gsg4AGQghAEgFAUQgFATAbAKQA2AUAZA8QAXA3ABBfQAABxgrBBQgrBChKAAQhLAAgphBQgrg/AAhyQAAhQAQg0QASg+AwgvQAegdBHgjQA9gfAigrQATgZABgVQACgTgQgEQgMgEgNANIgZAWQguAeg4gRQgvgPgjgoQgcgggogIQgcgGgfAHQgLADgEgHQgCgHAKgIQAbgVArACQAvACAfAcQAdAbAhAPQAjARAagGQARgDAAgOQABgOgTgHQgegLgng1Qgmg0g0gQQhOgWhLA9QhDA3gXBWQgGAXAMALQAMALAUgKQA7gZAuAWQAJAEAhAVQAcARAWAJQAsARA7gLIAGAAQAIAAACAHgAvDlPIBJDYQAHAXALAJQALAKATAAQATAAALgLQAKgLAJggICImzQAGgWAHgJQAIgJALgCQAkgEgBAwIAAF+QAAAbgCAHQgBAEgFADQgEADgFAAIgQAAQgJAAgHAHQgGAHgBAJQAAAOAJAGQAJAFAVAAICbAAQAVAAAIgFQAHgFABgOQAAgKgGgHQgGgHgJAAIgQAAQgLAAgFgKQgCgKAAgYIAAiBQgBgeAGgGQAFgHAYABIBzAAQAYgBAHAIQACAEABAGIAAAeIAAB8QAAAbgCAHQgGAKgJAAIgRAAQgIAAgHAHQgGAHAAAJQgBAOAJAGQAIAFAWAAICaAAQAWAAAJgFQAJgGAAgOQAAgJgHgHQgGgHgKAAIgRAAQgEAAgFgDQgEgDgBgEQgEgKAAgYIAAl+QAAgXAEgKQABgEAEgDQAFgEAEAAIARAAQAKABAGgHQAHgHAAgKQgBgOgIgFQgJgGgWAAIiaAAQgWAAgJAGQgJAFABAOQgBAKAHAHQAGAHAKgBIARAAQAKAAAFALQACAGAAAbIAABpIAAAeQgBAHgCADQgHAHgYAAIhzAAQgYAAgFgGQgGgHABgdIAAhuQAAgYACgJQAFgLALAAIAQAAQAJABAGgHQAGgHAAgKQAAgOgIgFQgIgGgVAAIkmAAQgRAAgIAGQgIAFAAANQAAAWAcABQAeAEAAATQAAAIgEAMIheE7QgCAFgEABQgEAAgCgGIhfksQgIgZgBgLQAAgMAHgEQAFgFARgCQAcgFgBgSQAAgXgcAAIinAAQgdAAgBAaQABAJAFAFQAGAFANADQAOAFAHADQAHAFADAKIAmBtQAHAYgJAZIg+C3QgCAFgEAAQgFABgCgFIh0lIQgCgLAAgIQAAgKAGgFQAGgEAOgCQARgBAGgGQAIgEgBgLQAAgXgcAAIiuAAQgdAAAAAWQAAALAFAEQAFAGANACQAVAFAHAGQAHAIAJAaICnG/QAJAXALAKQAKAJATAAQAQAAAMgJQAIgIAJgZIBOjYQABgGAEAAQAFAAABAGgAOkiCQgGAHAAAJQAAAOAJAGQAHAFAWABIFigBQAaAAAFgVIANhCQADgQgFgJQgEgJgNABQgPAAgHAPIgIAQQgPAggvAAIhUAAQgkAAgPgGQgKgEgDgLQgDgLAAgiIAAhsQAAgZAIgFQAEgDAfAAIAmAAQAbAAAHADQAIADACANIAAAFQAEAXAUAAQANAAAGgJQAEgJAAgWIAAhIQAAgVgEgJQgGgKgNAAQgUAAgEAWIAAAFQgCANgHADQgIADgbAAIgmAAQgfAAgEgCQgIgGAAgaIAAhkQAAgiAIgJQAJgIAjgBIBQAAQAfABANAEQAPAFAFAPQAGAQADACQAHAOAOAAQANAAAEgJQAGgJgEgQIgMg7QgFgVgZAAIlTAAQgVAAgJAGQgJAFAAAOQAAAJAGAIQAIAGAIAAIARAAQAEAAAEAEQAEAEACAFQADAIAAAaIAAF7QAAAagDAIQgCAEgDADQgEAEgFAAIgRAAQgJAAgGAGgAHyiCQgGAHAAAJQAAAOAJAGQAIAFAVAAIE/AAQAaAAAFgVIAMhCQAEgQgFgJQgFgJgMABQgPAAgIAPIgHAQQgQAgguAAIgxAAQgZAAgMgCQgMgBgGgFQgIgFgCgJQgCgJAAgdIAAllQABgbACgFQADgMAOAAIATAAQAJABAHgHQAGgHABgKQgBgOgIgFQgKgGgXAAIicAAQgWAAgJAGQgJAFAAAOQAAAKAHAHQAGAHAKgBIARAAQALAAADAMQADAHAAAZIAAGBQAAAXgDAIQgBAEgEADQgFAEgEAAIgRAAQgJAAgGAGg");
	this.shape.setTransform(0,0,0.189,0.189);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgYAaQgKgLAAgPQAAgOAKgKQAKgLAOABQAPgBAKALQAKAKAAAOQAAAPgKALQgKAJgPABQgOgBgKgJgAAWAYIgPgVQANgBAAgNQAAgPgRAAIgTAAIAAAyIAJAAIAAgVIAFAAIAOAVIAKAAg");
	this.shape_1.setTransform(24.6,11.2,0.189,0.189);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgrAiQgFAAgEgDQgEgDAAgFIAAgtQAAgLANAAIA+AAQARAAAKAJQALAJAAAPQAAAQgLAJQgKAJgRAAg");
	this.shape_2.setTransform(-2.1,16,0.189,0.189);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgJAHIAAgNIAIAAQALAAAAAGQAAAHgNAAg");
	this.shape_3.setTransform(24.6,10.9,0.189,0.189);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhvCsQgog9AAhtQAAhtAog/QAog/BHAAQBGAAAoA/QAqBAAABqQAABrgpBAQgpA/hFAAQhIAAgog+g");
	this.shape_4.setTransform(-9.2,5.7,0.189,0.189);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgYAfQgIAAADgIIAZgyQABgDADAAQADAAACADIAZAzQABADgCACQAAAAgBABQAAAAgBAAQAAABgBAAQAAAAgBAAg");
	this.shape_5.setTransform(-8.4,16.6,0.189,0.189);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgtDtQgngDgNgHQgVgLAAghIAAljQAAghAKgMQAKgLAcgFIAdgDQBLAAAqA/QArA/AABvQAABxgrA/QgqA8hGAAIgJAAg");
	this.shape_6.setTransform(12.2,5.7,0.189,0.189);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhvCsQgog9AAhtQAAhtAog/QApg/BGAAQBFAAAqA/QApBAAABqQAABrgpBAQgpA/hGAAQhGAAgpg+g");
	this.shape_7.setTransform(1.3,5.7,0.189,0.189);

	this.instance = new lib.Path();
	this.instance.parent = this;
	this.instance.setTransform(0,0,0.189,0.189,0,0,0,168.1,168.1);
	this.instance.alpha = 0.551;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-33,-33,66,66);


(lib.seventeenrollover = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_0 = function() {
		this.stop();
	}
	this.frame_11 = function() {
		this.stop();
	}
	this.frame_23 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(11).call(this.frame_11).wait(12).call(this.frame_23).wait(7));

	// cta-rollover
	this.instance = new lib.seventeenvidrollover();
	this.instance.parent = this;
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1).to({alpha:1},9).wait(2).to({alpha:0},10).wait(8));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-64.5,-66.7,129,33.5);


// stage content:
(lib.wideskyscrapersixteen = function(mode,startPosition,loop) {
if (loop == null) { loop = false; }	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_34 = function() {
		//onhover event to reveal green cta rectangle over orange rectangle
		
		console.log("this frame works");
		this.btn_main.addEventListener("mouseover", fl_MouseOverHandler.bind(this));
		this.btn_main.addEventListener("mouseout", fl_MouseOutHandler.bind(this));
		
		function fl_MouseOverHandler()
		{
			this.cta_rollover.gotoAndPlay(2);
		}
		
		function fl_MouseOutHandler()
		{
		this.cta_rollover.gotoAndPlay(13);
		}
	}
	this.frame_89 = function() {
		this.stop();
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(34).call(this.frame_34).wait(55).call(this.frame_89).wait(2));

	// button
	this.btn_main = new lib.mainbutton();
	this.btn_main.parent = this;
	this.btn_main.setTransform(82.2,302,0.797,0.919,0,0,0,0.1,0.4);
	new cjs.ButtonHelper(this.btn_main, 0, 1, 2, false, new lib.mainbutton(), 3);

	this.timeline.addTween(cjs.Tween.get(this.btn_main).wait(91));

	// grey-rectangle
	this.instance = new lib.greyrectangle();
	this.instance.parent = this;
	this.instance.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(91));

	// fade-from-white
	this.instance_1 = new lib.whiterectanglefade();
	this.instance_1.parent = this;
	this.instance_1.setTransform(91,300.1);

	this.timeline.addTween(cjs.Tween.get(this.instance_1).to({alpha:0},9).wait(82));

	// white-logo
	this.instance_2 = new lib.whitelogo("synched",0);
	this.instance_2.parent = this;
	this.instance_2.setTransform(80,37);
	this.instance_2.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(9).to({scaleX:0.06,scaleY:0.06},0).to({scaleX:1.53,scaleY:1.53,alpha:1},6,cjs.Ease.get(1)).to({scaleX:1.42,scaleY:1.42,y:36.9},7,cjs.Ease.get(1)).wait(69));

	// shop-now
	this.instance_3 = new lib.seventeenordernow();
	this.instance_3.parent = this;
	this.instance_3.setTransform(80,383);
	this.instance_3.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(34).to({alpha:1},10).wait(47));

	// cta-rollover
	this.cta_rollover = new lib.seventeenrollover();
	this.cta_rollover.parent = this;
	this.cta_rollover.setTransform(80,382.8);
	this.cta_rollover.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.cta_rollover).wait(34).to({alpha:1},10).wait(47));

	// cta-rectangle
	this.instance_4 = new lib.seventeenrectangle();
	this.instance_4.parent = this;
	this.instance_4.setTransform(80,382.8);
	this.instance_4.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(34).to({alpha:1},10).wait(47));

	// delicious-memories
	this.instance_5 = new lib.deliciiousmemories();
	this.instance_5.parent = this;
	this.instance_5.setTransform(80,176.8);
	this.instance_5.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(22).to({alpha:1},10).wait(59));

	// holiday-mains-sides
	this.instance_6 = new lib.holidaymainssides();
	this.instance_6.parent = this;
	this.instance_6.setTransform(80,252.7);
	this.instance_6.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(22).to({alpha:1},10).wait(59));

	// greens
	this.instance_7 = new lib.sixteengreens_1();
	this.instance_7.parent = this;
	this.instance_7.setTransform(133.5,54);
	this.instance_7.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(49).to({alpha:1},10).wait(32));

	// pie
	this.instance_8 = new lib.sixteenpie_1();
	this.instance_8.parent = this;
	this.instance_8.setTransform(37.5,78.5);
	this.instance_8.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(54).to({alpha:1},10).wait(27));

	// meats
	this.instance_9 = new lib.sixteenmeats_1();
	this.instance_9.parent = this;
	this.instance_9.setTransform(103.5,506.5);
	this.instance_9.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(59).to({alpha:1},10).wait(22));

	// spinach
	this.instance_10 = new lib.sixteenspinach_1();
	this.instance_10.parent = this;
	this.instance_10.setTransform(33.5,554);
	this.instance_10.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_10).wait(64).to({alpha:1},10).wait(17));

	// blue
	this.instance_11 = new lib.sixteenblue_1();
	this.instance_11.parent = this;
	this.instance_11.setTransform(27,471);
	this.instance_11.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_11).wait(69).to({alpha:1},10).wait(12));

	// candle
	this.instance_12 = new lib.sixteencanlde_1();
	this.instance_12.parent = this;
	this.instance_12.setTransform(149.5,392.7);
	this.instance_12.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance_12).wait(74).to({alpha:1},10).wait(7));

	// table
	this.instance_13 = new lib.sixteentable_1();
	this.instance_13.parent = this;
	this.instance_13.setTransform(80,300);

	this.timeline.addTween(cjs.Tween.get(this.instance_13).wait(91));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(68,274,206.1,652.2);
// library properties:
lib.properties = {
	id: '85088BD5353243C8B4895C262600CED3',
	width: 160,
	height: 600,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/index_atlas_.png?1510850435914", id:"index_atlas_"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['85088BD5353243C8B4895C262600CED3'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;